---

- include_tasks: setup-licensing.yaml
  when: bigiq_onboard_license_key|default(False)

- include_tasks: setup-node-type.yaml

- include_tasks: setup-management-address.yaml

- include_tasks: setup-services.yaml

- include_tasks: setup-master-passphrase.yaml

- include_tasks: setup-passwords.yaml

- include_tasks: setup-hostname.yaml

- include_tasks: setup-mark-system-setup.yaml

- name: Reboot device
  uri:
    url: "https://{{ provider.server }}:{{ provider.server_port }}/mgmt/shared/failover-state"
    method: PATCH
    timeout: "{{ bigiq_onboard_timeout }}"
    validate_certs: "{{ bigiq_onboard_validate_certs }}"
    user: "{{ bigiq_onboard_user }}"
    password: "{{ bigiq_onboard_credentials_password }}"
    body:
      restart: True
    body_format: json

- name: Wait for device to go offline
  pause:
    seconds: 30

- name: Wait for BIG-IQ to be available
  uri:
    url: "https://{{ provider.server }}:{{ provider.server_port }}/info/system"
    timeout: "{{ bigiq_onboard_timeout }}"
    validate_certs: "{{ bigiq_onboard_validate_certs }}"
  register: status
  until: status is success and status.json.available|bool
  retries: 60
  delay: 5
